WITH
	HYPERCUBES AS (
		SELECT
			FIRST_PC_ID,
			PREPARED_ID,
			TIME_START,
			X_START,
			Y_START,
			Z_START,
			TILE_NAME,
			TIME_SIZE,
			OCCUPANCY_RATIOS[:16] AS OCCUPANCY_RATIOS_CH_0,
			OCCUPANCY_RATIOS[16 + 1:] AS OCCUPANCY_RATIOS_CH_1,
			METADATA_JSON,
			CHANNEL_TARGETS
		FROM
			PUBLIC.AGGREGATE_MVIEW_FROM_TABLE_PARTITIONS ('prepared_cubes'::TEXT, 16)
	) -- Upsert the current rows
INSERT INTO
	PUBLIC.MVIEW_TABLE_16_128_128_128_2
SELECT
	*
FROM
	HYPERCUBES;

-- NOTICE:  Complete.  00:05:56.776843 total elapsed
-- INSERT 0 1264476
-- Query returned successfully in 6 min 36 secs.
WITH
	HYPERCUBES AS (
		SELECT
			FIRST_PC_ID,
			PREPARED_ID,
			TIME_START,
			X_START,
			Y_START,
			Z_START,
			TILE_NAME,
			TIME_SIZE,
			OCCUPANCY_RATIOS[:1] AS OCCUPANCY_RATIOS_CH_0,
			OCCUPANCY_RATIOS[1 + 1:] AS OCCUPANCY_RATIOS_CH_1,
			METADATA_JSON,
			CHANNEL_TARGETS
		FROM
			PUBLIC.AGGREGATE_MVIEW_FROM_TABLE_PARTITIONS ('prepared_cubes'::TEXT, 1)
	) -- Upsert the current rows
INSERT INTO
	PUBLIC.MVIEW_TABLE_1_128_128_128_2
SELECT
	*
FROM
	HYPERCUBES;

-- NOTICE:  Complete.  00:06:39.702381 total elapsed
-- INSERT 0 17233956
-- Query returned successfully in 12 min 48 secs.
REFRESH MATERIALIZED VIEW MVIEW_ALL_METADATA_JSON_256; -- Query returned successfully in 10 min 43 secs.
REFRESH MATERIALIZED VIEW MVIEW_METADATA_JSON_256_2DARRAY;
REFRESH MATERIALIZED VIEW MVIEW_PC_128_256_256;
REFRESH MATERIALIZED VIEW PREPARED_16_128_256_256_2_HYPERCUBE_VIEW;