\timing on
SELECT
	HC.FIRST_PC_ID,
	HC.PREPARED_ID,
	HC.TIME_START,
	HC.X_START,
	HC.Y_START,
	HC.Z_START,
	HC.TIME_SIZE,
	HC.METADATA_JSON AS PC_METADATA_JSON,
	P.CHANNEL_SIZE,
	P.CUBE_SIZE,
	HC.TILE_NAME,
	HC.CHANNEL_TARGETS,
	HC.OCCUPANCY_RATIOS_CH_0,
	HC.OCCUPANCY_RATIOS_CH_1,
	P.SERVER_FOLDER,
	P.OUTPUT_FOLDER,
	P.METADATA_JSON AS P_METADATA_JSON,
	P."exists",
	P.EXISTS_PRFS,
	P.EXISTS_AWS,
	P.EXISTS_OAK,
	PT.METADATA_TILE_JSON,
	GS.JSON_EXCITE_MAP_TOTAL,
	GS."Unique Targets" AS UNIQUE_TARGETS,
	GS."Imaged Locations" AS IMAGED_LOCATIONS,
	GS."Date crossed" AS DATE_CROSSED,
	GS.HPF,
	P.IS_SYNTHETIC
FROM
	MVIEW_TABLE_16_128_128_128_2 HC
	LEFT JOIN PREPARED P ON P.ID = HC.PREPARED_ID
	LEFT JOIN PREPARED_TILES PT ON HC.PREPARED_ID = PT.PREPARED_ID
	AND HC.TILE_NAME = PT.TILE_NAME
	LEFT JOIN G_SHEET_MASTER_IMAGING_LIST GS ON GS."Data location" = P.DATA_LOCATION
LIMIT
	30000;