_target_: models.maskedautoencoder.MaskedAutoEncoder
input_fmt: ${dataset_layout_order}
input_shape: ${eval:"[${clusters.batch_size_per_gpu}] + ${datasets.input_shape}"}
temporal_patch_size: ${datasets.patch_shape.0}
lateral_patch_size: ${datasets.patch_shape.1}
axial_patch_size: ${datasets.patch_shape.2}

embed_dim: 4096
decoder_embed_dim: 512
depth: 32
decoder_depth: 8
num_heads: 32
decoder_num_heads: 8
mlp_ratio: 4.0

proj_drop_rate: 0.0
att_drop_rate: 0.0
drop_path_rate: 0.1
init_std: 0.02
fixed_dropout_depth: false
use_conv_proj: false
norm_layer: RmsNorm
act_layer: SiLU
mlp_layer: SwiGLU

mask_ratio: 0.75
window_mask_shape: null