defaults:
  - _self_

_target_: data.databases.supabase_database.SupabaseDatabase
dbname: 'staging'

num_timepoints: ${datasets.input_shape.0} # number of timepoints for each hypercube

max_rois: null # maximum number of ROIs (each ROI can have dozens of tiles)
max_tiles: null # maximum number of tiles (each tile can have thousands of hypercubes)
max_hypercubes: 100 # maximum number of hypercubes to return

hpf_list: null # list of specific HPFs (hours-post-fertilization in hours) to filter
roi_list: null # list of specific ROIs to filter
tile_list: null # list of specific tiles to filter
verbose: true # to print debug messages
fetch_hypercubes_dataframe: true # automatically initialize the database based on the provided parameters
hypercubes_dataframe_path: ${paths.outdir}/database/hypercubes_dataframe.csv # path to the hypercubes dataframe (path/to/repo/databases/default_hypercubes_dataframe.csv)
use_cached_hypercubes_dataframe: false # if True, will use the cached hypercubes dataframe from the given path
protocol: binary # protocol used to fetch data from source (default is 'binary', can also be 'csv' or 'cursor')