
# no adapter
input_shape_metadata:
  "1":
    channels: ${models.backbones.masked_encoder.embed_dim}
    stride: 16

transformer_in_features: ["1"]
target_min_stride: null # not used
total_num_feature_levels: 1
transformer_encoder_dropout: 0.1
transformer_encoder_num_heads: 8
transformer_encoder_dim_feedforward: 1024
num_transformer_encoder_layers: 4
conv_dim: 384
mask_dim: 256
norm: null
dtype: ${quantization}
use_deform_attention: false