# BUILD: cell_observatory_platform.models.backbones.plain_detr_backbone.BUILD
# backbone_embed_dims: 
#   - ${models.backbones.masked_encoder.embed_dim} # [1024, 1024, 1024, 1024]x4 if using all layers
#   - ${models.backbones.masked_encoder.embed_dim}
#   - ${models.backbones.masked_encoder.embed_dim}
#   - ${models.backbones.masked_encoder.embed_dim}
# train_backbone: true
# use_layernorm: true
# blocks_to_train: null
# out_layers: [10, 14, 18, 23] # OR: [10, 14, 18, 22] for multi-scale features
# adapter_out_layers: [2] # [0, 1, 2, 3] to use all adapter features
# backbone_args: ${models.backbones.masked_encoder}
# backbone_output_format: feature
# input_shape: ${datasets.input_shape}
# patch_shape: ${datasets.patch_shape}
# input_format: ${dataset_layout_order}

BUILD: cell_observatory_platform.models.backbones.plain_detr_backbone.BUILD
backbone_embed_dims: 
  - ${models.backbones.masked_encoder.embed_dim} # [1024, 1024, 1024, 1024]x4 if using all layers
train_backbone: true
use_layernorm: true
blocks_to_train: null
out_layers: null # OR: [10, 14, 18, 22] for multi-scale features
adapter_out_layers: null # [[0, 1, 2, 3] to use all adapter features
backbone_args: ${models.backbones.masked_encoder}
backbone_output_format: sequence
input_shape: ${datasets.input_shape}
patch_shape: ${datasets.patch_shape}
input_format: ${dataset_layout_order}