_target_: models.vit.ViT
input_fmt: ${dataset_layout_order}
input_shape: ${datasets.input_shape}
patch_shape: ${datasets.patch_shape}
embed_dim: 768
depth: 12
num_heads: 12
mlp_ratio: 4.0
proj_drop_rate: 0.0
att_drop_rate: 0.0
drop_path_rate: 0.1
init_std: 0.02
fixed_dropout_depth: false
global_pool: avgmax
use_conv_proj: false
norm_layer: LayerNorm
act_layer: GELU
mlp_layer: Mlp