# @package _global_

# TODO: make an example/template multi-run config

# specify multi_run for launching several training jobs
run_type: multi_run

# NOTE (IMPORTANT): 
# We have two ways of grouping keeping tabs of training jobs that may later be compared:
# 1. all jobs will have same rootdir with prefix given by 
#    `name` field in each run config
# 2. wandb_tags to group runs together in the wandb dashboard
#    and use their hparam features to compare runs 

wandb_tags: [ "benchmark", "benchmark_training_infra", "scaling", "h100", "mae_large"]
data_base_dir: training_infrastructure/training_mae_4d

# NOTE: make sure to include .yaml suffix to naming of config files! These names are appended to configs/experiments/
#       and written to disk for reproducibility and to be passed to runner.py

# NOTE: defaults_overrides is a list of configs that will be merged into the run config
#       before applying the run overrides. This is useful for setting defaults to something different
#      than the global defaults, e.g. for a specific dataloader or model.

runs:
#  - cfg: benchmarks/janelia/benchmark_training_base
#    name: 1gpus_8cores_h100_mae_large.yaml
#    defaults_overrides:
#      - clusters: clusters/janelia_h100
#    overrides:
#      clusters:
#        batch_size: 32 # total batch size
#        worker_nodes: 1 # number of worker nodes
#        gpus_per_worker: 1 # number of gpus per worker node
#        cpus_per_gpu: 8 # number of cpu cores per gpu
#        mem_per_cpu: 40000 # ram per cpu core
#        scaling_config:
#          use_gpu: true
#          num_workers: ${clusters.total_gpus} # number of total workers (equals total nr. gpus normally)
#          resources_per_worker:
#            CPU: 0
#            GPU: 1
#          trainer_resources:
#            CPU: 0
  - cfg: benchmarks/janelia/benchmark_training_base
    name: 4gpus_8cores_h100_mae_large.yaml
    defaults_overrides:
      - clusters: clusters/janelia_h100
    overrides:
      clusters:
        batch_size: 128 # total batch size
        worker_nodes: 1 # number of worker nodes
        gpus_per_worker: 4 # number of gpus per worker node
        cpus_per_gpu: 8 # number of cpu cores per gpu
        mem_per_cpu: 40000 # ram per cpu core
        scaling_config:
          use_gpu: true
          num_workers: ${clusters.total_gpus} # number of total workers (equals total nr. gpus normally)
          resources_per_worker:
            CPU: 0
            GPU: 1
          trainer_resources:
            CPU: 0
      hooks:
        nsys_env:
          nsight:
            pytorch: autograd-shapes-nvtx
            t: cuda,nvtx,cudnn,cublas,osrt
            s: cpu
            # "gpu-metrics-devices": all
            capture-range: cudaProfilerApi
            capture-range-end: stop-shutdown
        hooks_list:
          - _target_: training.hooks.NsysProfilerHook
            start_iter: 80
            end_iter: 90
  - cfg: benchmarks/janelia/benchmark_training_base
    name: 8gpus_8cores_h100_mae_large.yaml
    defaults_overrides:
      - clusters: clusters/janelia_h100
    overrides:
      clusters:
        batch_size: 256 # total batch size
        worker_nodes: 1 # number of worker nodes
        gpus_per_worker: 8 # number of gpus per worker node
        cpus_per_gpu: 8 # number of cpu cores per gpu
        mem_per_cpu: 40000 # ram per cpu core
        scaling_config:
          use_gpu: true
          num_workers: ${clusters.total_gpus} # number of total workers (equals total nr. gpus normally)
          resources_per_worker:
            CPU: 0
            GPU: 1
          trainer_resources:
            CPU: 0
      hooks:
        nsys_env:
          nsight:
            pytorch: autograd-shapes-nvtx
            t: cuda,nvtx,cudnn,cublas,osrt
            s: cpu
            # "gpu-metrics-devices": all
            capture-range: cudaProfilerApi
            capture-range-end: stop-shutdown
        hooks_list:
          - _target_: training.hooks.NsysProfilerHook
            start_iter: 80
            end_iter: 90