# @package _global_
defaults:
  - /paths/janelia                           # configs/paths/janelia.yaml
  - /hydra/overrides                         # configs/hydra/overrides.yaml (not working)
  - /clusters/local                          # configs/clusters/local.yaml
  - /datasets/pretrain_dataset_ray           # configs/datasets/pretrain_dataset.yaml
  - /models/mae/large                        # configs/models/mae/large.yaml
  - /hooks/hooks                             # configs/hooks/hooks.yaml
  - /checkpoint/checkpoint                   # configs/checkpoint/checkpoint.yaml
  - /loggers/loggers                         # configs/loggers/loggers.yaml
  - /evaluation/base_evaluator               # configs/evaluation/base_evaluator.yaml
  - /deepspeed/zero2                         # configs/deepspeed/zero2.yaml
  - /optimizers/lamb                         # configs/optimizers/lamb.yaml
  - /schedulers/test_warmup_cosine_decay     # configs/schedulers/test_warmup_cosine_decay.yaml
  - /optimizations/optimizations             # configs/optimizations/optimizations.yaml
  - /profiling/profiling                      # configs/profiling/profiling.yaml
  - _self_

# experiment name (used for logging)
experiment_name: benchmark_dataloader_ray_v2_h200
wandb_project: benchmark_dataloader_ray_v2

# task
task: pretrain_mae

# Model type
network: mae

# engine type
engine: deepspeed

# distributed framework
distributed_framework: ray

# run type
run_type: single_run # single_run, multi_run, or tune

# job type
job_type: train # train or test

# trainer type
trainer: training.loops.EpochBasedTrainer

# loop per worker script
loop_per_worker_script: training.loops.train_loop_per_worker

# training quantization
quantization: bfloat16 # data type for training, options: bfloat16, float32, float16

# dtype for training data
dataset_dtype: bfloat16 # data type for training, options: bfloat16, float32, float16
storage_dtype: uint16 # data type for storage

# dataset layout in the zarr files
dataset_layout_order: TZYXC

# overrides
# --------------------------------------------------------------------------------

# clusters
clusters:
  batch_size: 448 # total batch size
  worker_nodes: 1 # number of worker nodes
  gpus_per_worker: 8 # number of gpus per worker node
  cpus_per_gpu: 12 # number of cpu cores per gpu
  mem_per_cpu: 40000 # ram per cpu core
  ray_queue_memory: 0.35
  scaling_config:
    use_gpu: true
    num_workers: ${clusters.total_gpus} # number of total workers (equals total nr. gpus normally)
    resources_per_worker:
      CPU: 1
      GPU: 1
    trainer_resources:
      CPU: 0 

#paths:
paths:
  # base output directory for logs, checkpoints, etc.
  outdir: ${paths.data_path}/pretrained_models/${experiment_name}
  resume_checkpointdir: null
  pretrained_checkpointdir: null

# data
datasets:
  # mainly used by other configs but determined here for ease of access
  batch_size: ${clusters.batch_size_per_gpu} # batch size = (total_batch_size * total_gpus)
  input_shape: [16, 128, 128, 128, 2] # NOTE: important that this matches database hypercube shape
  patch_shape: [4, 16, 16, 16]

  databases:
    max_rois: null # maximum number of ROIs (each ROI can have dozens of tiles)
    max_tiles: null # maximum number of tiles (each tile can have thousands of hypercubes)
    max_hypercubes: 50000 # maximum number of hypercubes to return
    use_cached_hypercubes_dataframe: true # whether to use the cached hypercubes dataframe
    hypercubes_dataframe_path: /groups/betzig/betziglab/CellObservatoryData/databases/hypercubes_dataframe.csv
    roi_list: [576]
    server_folder_path: /groups/betzig/betziglab/CellObservatoryData/read_speed_tests/large_test_zarrs
    protocol: cursor # protocol used to fetch data from source (default is 'binary', can also be 'csv' or 'cursor')

# schedulers
schedulers:
  epochs: 2

# hooks
hooks:
  # nsys_env:
  #   nsight: 
  #     pytorch: autograd-shapes-nvtx
  #     t: cuda,nvtx,cudnn,cublas,osrt
  #     s: cpu
  #     # "gpu-metrics-devices": 0
  #     capture-range: cudaProfilerApi
  #     capture-range-end: stop-shutdown
  hooks_list:
  # - _target_: training.hooks.NsysProfilerHook
  #   start_iter: 20
  #   end_iter: 25
  - _target_: training.hooks.FreeDeviceBufferHook
  - _target_: training.hooks.AnomalyDetector
  - _target_: training.hooks.LRScheduler
  - _target_: training.hooks.IterationTimer
  - _target_: training.hooks.PeriodicWriter
  - _target_: training.hooks.PeriodicCheckpointer
    period: 1
    file_prefix: latest_model
  - _target_: training.hooks.BestCheckpointer
    checkpointdir: ${checkpoint.checkpoint_manager.save_checkpointdir}
  - _target_: training.hooks.TorchMemoryStats
    step_period: 2
    epoch_period: 1
    logdir: ${loggers.logdir}
  - _target_: training.hooks.BestMetricSaver
    metric_name: ${evaluation.val_metric}
    compare_fn: ${evaluation.val_mode}
    eval_after_validation: true