# @package _global_

# TODO: make an example/template multi-run config

# specify multi_run for launching several training jobs
run_type: multi_run

# NOTE (IMPORTANT): 
# We have two ways of grouping keeping tabs of training jobs that may later be compared:
# 1. all jobs will have same rootdir with prefix given by 
#    `name` field in each run config
# 2. wandb_tags to group runs together in the wandb dashboard
#    and use their hparam features to compare runs 

wandb_tags: [ "benchmark", "benchmark_training_infra", "scaling", "h100", "mae_large"]
data_base_dir: training_infrastructure/training_mae_4d

# NOTE: make sure to include .yaml suffix to naming of config files! These names are appended to configs/experiments/
#       and written to disk for reproducibility and to be passed to runner.py

# NOTE: defaults_overrides is a list of configs that will be merged into the run config
#       before applying the run overrides. This is useful for setting defaults to something different
#      than the global defaults, e.g. for a specific dataloader or model.

runs:
  - cfg: benchmarks/janelia/benchmark_training_base
    name: 8xh100_mae_large_run1.yaml
    defaults_overrides:
      - clusters: clusters/janelia_h100
    overrides:
      clusters:
        batch_size: 256 # total batch size
        worker_nodes: 1 # number of worker nodes
        gpus_per_worker: 8 # number of gpus per worker node
        cpus_per_gpu: 12 # number of cpu cores per gpu
        mem_per_cpu: 40000 # ram per cpu core
  - cfg: benchmarks/janelia/benchmark_training_base
    name: 8xh100_mae_large_run2.yaml
    defaults_overrides:
      - clusters: clusters/janelia_h100
    overrides:
      clusters:
        batch_size: 256 # total batch size
        worker_nodes: 1 # number of worker nodes
        gpus_per_worker: 8 # number of gpus per worker node
        cpus_per_gpu: 12 # number of cpu cores per gpu
        mem_per_cpu: 40000 # ram per cpu core
  - cfg: benchmarks/janelia/benchmark_training_base
    name: 8xh100_mae_large_run3.yaml
    defaults_overrides:
      - clusters: clusters/janelia_h100
    overrides:
      clusters:
        batch_size: 256 # total batch size
        worker_nodes: 1 # number of worker nodes
        gpus_per_worker: 8 # number of gpus per worker node
        cpus_per_gpu: 12 # number of cpu cores per gpu
        mem_per_cpu: 40000 # ram per cpu core
  - cfg: benchmarks/janelia/benchmark_training_base
    name: 8xh100_mae_large_run4.yaml
    defaults_overrides:
      - clusters: clusters/janelia_h100
    overrides:
      clusters:
        batch_size: 256 # total batch size
        worker_nodes: 1 # number of worker nodes
        gpus_per_worker: 8 # number of gpus per worker node
        cpus_per_gpu: 12 # number of cpu cores per gpu
        mem_per_cpu: 40000 # ram per cpu core
  - cfg: benchmarks/janelia/benchmark_training_base
    name: 16xh100_mae_large_run1.yaml
    defaults_overrides:
      - clusters: clusters/janelia_h100
    overrides:
      clusters:
        batch_size: 512 # total batch size
        worker_nodes: 2 # number of worker nodes
        gpus_per_worker: 8 # number of gpus per worker node
        cpus_per_gpu: 12 # number of cpu cores per gpu
        mem_per_cpu: 40000 # ram per cpu core
  - cfg: benchmarks/janelia/benchmark_training_base
    name: 24xh100_mae_large_run1.yaml
    defaults_overrides:
      - clusters: clusters/janelia_h100
    overrides:
      clusters:
        batch_size: 768 # total batch size
        worker_nodes: 3 # number of worker nodes
        gpus_per_worker: 8 # number of gpus per worker node
        cpus_per_gpu: 12 # number of cpu cores per gpu
        mem_per_cpu: 40000 # ram per cpu core
  - cfg: benchmarks/janelia/benchmark_training_base
    name: 32xh100_mae_large_run1.yaml
    defaults_overrides:
      - clusters: clusters/janelia_h100
    overrides:
      clusters:
        batch_size: 1024 # total batch size
        worker_nodes: 4 # number of worker nodes
        gpus_per_worker: 8 # number of gpus per worker node
        cpus_per_gpu: 12 # number of cpu cores per gpu
        mem_per_cpu: 40000 # ram per cpu core
  - cfg: benchmarks/janelia/benchmark_training_base
    name: 8xh200_mae_large_run1.yaml
    defaults_overrides:
      - clusters: clusters/janelia_h200
    overrides:
      clusters:
        batch_size: 256 # total batch size
        worker_nodes: 1 # number of worker nodes
        gpus_per_worker: 8 # number of gpus per worker node
        cpus_per_gpu: 12 # number of cpu cores per gpu
        mem_per_cpu: 40000 # ram per cpu core
  - cfg: benchmarks/janelia/benchmark_training_base
    name: 8xh200_mae_large_run1.yaml
    defaults_overrides:
      - clusters: clusters/janelia_h200
    overrides:
      clusters:
        batch_size: 512 # total batch size
        worker_nodes: 2 # number of worker nodes
        gpus_per_worker: 8 # number of gpus per worker node
        cpus_per_gpu: 12 # number of cpu cores per gpu
        mem_per_cpu: 40000 # ram per cpu core