defaults:
  - _self_  

val_begin: 0
val_interval: 1
val_metric: step_loss 
val_mode: min # 'min' or 'max'

evaluator:
  name: base
  training_metrics:
    - name: train_loss
      key: step_loss
      reduce_method: mean