name: channel_split

with_masking: false
mask_generator: ${datasets.masking.mask_generators.0}
dtype: ${quantization}

transforms_list:
  - _target_: cell_observatory_platform.data.transforms.normalize.Normalize
    input_layout:
      _target_: cell_observatory_platform.data.data_shapes.MULTICHANNEL_HYPERCUBE
      value: ${dataset_layout_order}

patch_shape: ${datasets.patch_shape}
input_format: ${dataset_layout_order}
input_shape: ${datasets.input_shape}
mask_channel_idx: ${datasets.mask_channel_idx}

seed: ${seed}