_target_: cell_observatory_platform.inference.inferencer.InferencerWorker

use_cached_hypercubes_dataframe: ${datasets.databases.use_cached_hypercubes_dataframe}
hypercubes_dataframe_path: ${datasets.databases.hypercubes_dataframe_path}

input_format: ${dataset_layout_order} 
timepoint_list: ${datasets.databases.timepoint_list}

task: null
inference_mode: "sliding_window"
decoder_head_type: "pretrain"

roi_tile_list: null

protocol: ${datasets.databases.protocol}
dotenv_path: null
dbname: ${datasets.databases.dbname}
server_folder_path: ${paths.server_folder_path}
verbose: false
max_hypercubes: null
max_partitions: 10
num_save_workers: 2

save_dir: ${paths.outdir}/inference

save_as_pdf: true
save_as_volume: false
z_step_pdf: 10

# TIFF OPTION:
# save_format: "tiff"
# zarr_chunk_shape: null
# zarr_shard_shape: null

# ZARR OPTION:
save_format: "zarr"
zarr_chunk_shape: [32, 32, 32]
zarr_shard_shape: [128, 128, 128]

outputs_metadata:
  predictions: 
    activation: null
    num_output_channels: 2

auxiliary_outputs:
  data_tensor:
    activation: null
    num_output_channels: 2