BASE:
  - _target_: cell_observatory_platform.data.transforms.normalize.Normalize
    input_layout:
      _target_: cell_observatory_platform.data.data_shapes.MULTICHANNEL_HYPERCUBE
      value: ${dataset_layout_order}
  - _target_: cell_observatory_platform.data.transforms.multicrop.MultiCrop3D
    crop_transforms:
      - _target_: cell_observatory_platform.data.transforms.crop.Crop
        input_format: ZYXC
        target_spatial_shape: [64, 128, 128]
        crop_dims: ZYX
        crop_type: random
        dtype: bfloat16
      - _target_: cell_observatory_platform.data.transforms.crop.Crop
        input_format: ZYXC
        target_spatial_shape: [32, 64, 64]
        crop_dims: ZYX
        crop_type: random
        dtype: bfloat16
    names:
      - global_crops
      - local_crops
    counts:
      - 2   # n_global_crops
      - 8   # n_local_crops (must match meta_arch dino local_crops_number)