# @package _global_
defaults:
  - /paths/abc                               # configs/paths/abc.yaml
  - /hydra/overrides                         # configs/hydra/overrides.yaml (not working)
  - /clusters/abc_a100                       # configs/clusters/abc_a100.yaml
  - /datasets/pretrain_dataset               # configs/datasets/pretrain_dataset.yaml
  - /models/mae/base                         # configs/models/mae/base.yaml
  - /hooks/hooks                             # configs/hooks/hooks.yaml
  - /checkpoint/checkpoint                   # configs/checkpoint/checkpoint.yaml
  - /loggers/loggers                         # configs/loggers/loggers.yaml
  - /evaluation/base_evaluator               # configs/evaluation/base_evaluator.yaml
  - /deepspeed/zero3                         # configs/deepspeed/zero3.yaml
  - /optimizers/lamb                         # configs/optimizers/lamb.yaml
  - /schedulers/test_warmup_cosine_decay     # configs/schedulers/test_warmup_cosine_decay.yaml
  - _self_


# experiment name (used for logging)
experiment_name: benchmark_training_4d_mae

# task
task: pretrain_mae

# Model type
network: mae

# engine type
engine: deepspeed

# distributed framework
distributed_framework: ray

# job type
job_type: train # train or test

# trainer type
trainer: training.loops.EpochBasedTrainer

# loop per worker script
loop_per_worker_script: scripts.benchmark_training.bench_training

# training quantization
quantization: float16 # data type for training, options: float32, float16

# where to save the benchmark csv results
csv_outdir: ${paths.data_path}/nvme/segment_4d/benchmarks/training_4d/results

# dtype for training data
dataset_dtype: float16 # data type for training, options: float32, float16

# dataset layout in the zarr files
dataset_layout_order: TZYXC

# overrides
# --------------------------------------------------------------------------------

paths:
  # base output directory for logs, checkpoints, etc.
  outdir: ${paths.data_path}/nvme/segment_4d/benchmarks/training_4d/runs

clusters:
  launcher_type: local # type of launcher to use

  batch_size: 4
  worker_nodes: 1 # number of worker nodes
  gpus_per_worker: 4 # number of gpus per worker node
  cpus_per_gpu: 3 # number of cpu cores per gpu
  mem_per_cpu: 31000 # ram per cpu core

datasets:
  # mainly used by other configs but determined here for ease of access
  batch_size: ${clusters.batch_size_per_gpu} # batch size = (total_batch_size * total_gpus)
  input_shape: [16, 128, 128, 128, 2] # NOTE: important that this matches database hypercube shape
  patch_shape: [4, 16, 16, 16]

  split: 0.1

  prefetch_factor: 2 # prefetch factor for the dataloader
  num_workers: ${clusters.cpus_per_worker}  # number of workers for the dataloader

  databases:
    max_hypercubes: 200

models:
  _target_: models.maskedautoencoder.MaskedAutoEncoder
  input_fmt: BTZYXC
  input_shape: ${eval:"[${clusters.batch_size_per_gpu}] + ${datasets.input_shape}"}
  temporal_patch_size: ${datasets.patch_shape.0}
  lateral_patch_size: ${datasets.patch_shape.1}
  axial_patch_size: ${datasets.patch_shape.2}

# hooks
hooks:
  hooks_list:
  - _target_: training.hooks.AnomalyDetector
  - _target_: training.hooks.SamplerSetter
  - _target_: training.hooks.LRScheduler
  - _target_: training.hooks.IterationTimer
    warmup_iter: 2
  - _target_: training.hooks.PeriodicWriter
  - _target_: training.hooks.PeriodicCheckpointer
    period: 1
    file_prefix: latest_model
  - _target_: training.hooks.BestCheckpointer
    checkpointdir: ${checkpoint.checkpoint_manager.save_checkpointdir}
  - _target_: training.hooks.TorchMemoryStats
    step_period: 2
    epoch_period: 1
    logdir: ${loggers.logdir}
  - _target_: training.hooks.BestMetricSaver
    metric_name: ${evaluation.val_metric}
    compare_fn: ${evaluation.val_mode}
    eval_after_validation: true

deepspeed:
  wall_clock_breakdown: true

evaluation:
  val_begin: 0
  val_interval: 1
  # used by BestMetricSaver to save best metric
  # needs to match one of metrics saved per epoch by loss_dict
  # in the training loop or evaluator.evaluate() in the evaluation loop
  val_metric: val_step_loss
  val_mode: min
  evaluator:
    _target_: evaluation.base_evaluation.BaseEvaluator
    training_metrics:
      - "step_loss": "mean"

# Hydra sweeping configuration for benchmarks 
# --------------------------------------------------------------------------------

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      # cartesian product of the lists
      clusters.worker_nodes: 1, 2 # , 2, 3, 4 # number of worker nodes
      models._target_: models.maskedautoencoder.MaskedAutoEncoder #, models.jepa.JEPA  # model type
      # deepspeed.zero_optimization.stage: 1 #, 2, 3 # deepspeed zero optimization stage