defaults:
  - _self_

logdir: ${paths.outdir}/logs

event_writers_list:
  _target_: training.loggers.EventWriterList
  
event_writers:
    - _target_: training.loggers.LocalEventWriter
      save_dir: ${loggers.logdir}
      step_scalars_prefix: step_logbook
      epoch_scalars_prefix: epoch_logbook
      scalars_save_format: csv
    - _target_: training.loggers.WandBEventWriter
      project: ${wandb_project}
      # entity: cell-observatory
      # save directory for W&B logs
      # will automatically append wandb folder
      # to the logdir
      dir: ${loggers.logdir}
      name: ${experiment_name}
      tags: 
        - pretrain
        - ${network}
        - ${job_type}
        - ${trainer}
        - ${engine}
        - ${quantization}
        - ${task}
      # step to resume from if resuming a run 
      # (if id is set to an existing run)
      resume_from: null
      # unique ID used for resuming a run
      # if not set, a new run will be created
      # if set, the run will be resumed
      # if the id does not exist, a new run will 
      # be created
      id: null
      notes: "First test run for wandb logging"
      # force=True implies user must be logged in to W&B
      # otherwise if force=False, W&B will log
      # locally and not upload to W&B
      force: true
      step_scalar_keys:
        - step_time_median
        - val_step_time_median

        - data_time_median
        - data_time_max
        - data_time_min

        - preprocess_time_median
        - masking_time_median

        - collate_time_median
        - collate_time_max
        - collate_time_min

        - slice_time_median
        - slice_time_max
        - slice_time_min

        - val_data_time_median
        - val_data_time_max
        - val_data_time_min
        
        - val_preprocess_time_median
        
        - val_masking_time_median
        
        - val_collate_time_median
        - val_collate_time_max
        - val_collate_time_min
        
        - val_slice_time_median
        - val_slice_time_max
        - val_slice_time_min

        - step_loss_median
        - lr_median
      epoch_scalar_keys:
        - epoch_time_median
        - step_time_median
        - val_time_median

        - data_time_median
        - data_time_max
        - data_time_min

        - preprocess_time_median
        - masking_time_median

        - collate_time_median
        - collate_time_max
        - collate_time_min

        - slice_time_median
        - slice_time_max
        - slice_time_min

        - val_data_time_median
        - val_data_time_max
        - val_data_time_min
        
        - val_preprocess_time_median
        - val_masking_time_median

        - val_collate_time_median
        - val_collate_time_max
        - val_collate_time_min
        
        - val_slice_time_median
        - val_slice_time_max
        - val_slice_time_min
        
        - val_step_time_median
        - val_step_loss_median
        - step_loss_median
        - lr_median
        - eta_median

event_recorder:
  _target_: training.loggers.EventRecorder