defaults:
  - _self_

resume_run: false # whether to resume from a previous run

# used by Ray Report
ray_checkpoint_config:
  num_to_keep: 3
  checkpoint_score_attribute: best_loss
  checkpoint_score_order: ${evaluation.val_mode} # 'min' or 'max'

checkpoint_manager:
  enable: false
  load_only: false
  async_mode: disabled
  create_seed_checkpoint: false
  enable_ft_dataloader_checkpoints: false
  initial_load_path: null
  initial_load_model_only: true
  initial_load_in_hf: false
  initial_load_in_hf_quantized: false
  last_save_model_only: true
  last_save_in_hf: false
  export_dtype: float32
  exclude_from_loading: []
  interval: 10000
  enable_first_step_checkpoint: false
  keep_latest_k: 3
  resume_checkpointdir: ${paths.resume_checkpointdir}
  pretrained_checkpointdir: ${paths.pretrained_checkpointdir}
  save_checkpointdir: ${paths.outdir}/checkpoints
  folder: ${save_checkpointdir}
  save_period: 1 # save every n epochs