#!/usr/bin/env bash
# Job chaining past the LSF wall-clock limit (clusters.chain_jobs > 1).
# Sourced by ray_lsf_cluster.sh right after the args are parsed.
#
#   - Each link submits ONE follower at start, held with -w "ended(<this job>)",
#     so exactly one job is pending at any time and the follower starts only
#     after this one has ended (finished, crashed, or killed by the run limit).
#   - Every link runs the trainer with resume_checkpointdir=<outdir>/checkpoints
#     (manager.py adds it): the first link finds no checkpoint and starts
#     fresh, the others resume from the latest DCP step.
#   - The trainer writes <outdir>/TRAINING_DONE when the budget is complete
#     (training/helpers.py: write_training_done). A link that finds it exits
#     in seconds without starting anything -- the one "excess" launch.
#   - Crash guard: every link records "<rc> <runtime_s> <jobid>" in
#     <outdir>/chain_last_exit at exit; a follower whose predecessor ran for
#     less than CHAIN_MIN_RUNTIME seconds (default 1200) without finishing
#     stops the chain (a config error must not burn chain_jobs slots).
#   - To stop a chain by hand: touch <outdir>/CHAIN_STOP, then bkill the
#     running job and its pending follower (bjobs -w | grep <job_name>).
#
# Env (set by manager.py through bsub -env): CHAIN_REMAINING (followers still
# allowed after this one), CHAIN_MIN_RUNTIME. Follower command: <outdir>/chain_resubmit.sh
# (generated by manager.py; expects PARENT_JOBID and CHAIN_REMAINING).

CHAIN_JOB_START_TS=$(date +%s)

chain_record_exit() {  # <rc> <outdir>
    local rc=$1 outdir=$2
    echo "$rc $(( $(date +%s) - CHAIN_JOB_START_TS )) ${LSB_JOBID:-none}" > "$outdir/chain_last_exit"
}

# chain_job_start <outdir>: gate + follower submission. Exits the script when
# there is nothing to do; otherwise installs the exit record and returns.
chain_job_start() {
    local outdir=$1 min_runtime=${CHAIN_MIN_RUNTIME:-1200}
    if [ -f "$outdir/TRAINING_DONE" ]; then
        echo "[chain] run complete ($outdir/TRAINING_DONE exists); nothing to do"
        exit 0
    fi
    if [ -f "$outdir/CHAIN_STOP" ]; then
        echo "[chain] $outdir/CHAIN_STOP present; not resuming and not resubmitting"
        exit 0
    fi
    if [ -f "$outdir/chain_last_exit" ]; then
        local prev_rc prev_runtime prev_job
        read -r prev_rc prev_runtime prev_job < "$outdir/chain_last_exit"
        if [ "${prev_runtime:-0}" -lt "$min_runtime" ]; then
            echo "[chain] previous job ${prev_job} exited ${prev_rc} after ${prev_runtime}s" \
                 "(< CHAIN_MIN_RUNTIME=${min_runtime}) without finishing; stopping the chain" >&2
            exit 1
        fi
        echo "[chain] resuming after job ${prev_job} (exit ${prev_rc} after ${prev_runtime}s)"
    fi
    trap 'chain_record_exit $? "'"$outdir"'"' EXIT
    if [ "${CHAIN_REMAINING:-0}" -gt 0 ]; then
        if [ ! -f "$outdir/chain_resubmit.sh" ]; then
            echo "[chain] WARNING: CHAIN_REMAINING=$CHAIN_REMAINING but $outdir/chain_resubmit.sh is missing; no follower" >&2
            return 0
        fi
        echo "[chain] submitting follower (${CHAIN_REMAINING} link(s) left after this one), held until job ${LSB_JOBID:-?} ends"
        PARENT_JOBID="${LSB_JOBID:?LSB_JOBID unset}" CHAIN_REMAINING=$((CHAIN_REMAINING - 1)) \
            bash "$outdir/chain_resubmit.sh" \
            || echo "[chain] WARNING: follower submission failed; this job continues, the chain ends here" >&2
    else
        echo "[chain] last link of the chain (CHAIN_REMAINING=0)"
    fi
}
