# @package _global_
defaults:
  - /paths/abc
  - _self_

# type of plot to generate and save dir
plot_type: training_infrastructure_benchmark

csv_outdir: ${paths.data_path}/pretrained_models/benchmark/training_infrastructure/training_mae_4d/results_torch_loader.csv
# csv_outdir: ${paths.data_path}/pretrained_models/benchmark/training_infrastructure/training_mae_4d/results_dali_loader.csv

# overwrite existing csv files
force_overwrite: false

# cfgs to summarize runs for (summarized together)
runs:
  2_GPUs_torch: 
    cfg: ${paths.data_path}/pretrained_models/benchmark/training_infrastructure/training_mae_4d/2_GPUs_torch/2_GPUs_torch.yaml
    metadata:
      dataloader: torch
  3_GPUs_torch:
    cfg: ${paths.data_path}/pretrained_models/benchmark/training_infrastructure/training_mae_4d/3_GPUs_torch/3_GPUs_torch.yaml
    metadata:
      dataloader: torch
  2_GPUs_dali:
    cfg: ${paths.data_path}/pretrained_models/benchmark/training_infrastructure/training_mae_4d/2_GPUs_dali/2_GPUs_dali.yaml
    metadata:
      dataloader: dali
  3_GPUs_dali:
    cfg: ${paths.data_path}/pretrained_models/benchmark/training_infrastructure/training_mae_4d/3_GPUs_dali/3_GPUs_dali.yaml
    metadata:
      dataloader: dali

# OPTIONS:
# 'world_size', 
# 'data_parallel_size', 
# 'model_parallel_size',
# 'batch_size_per_gpu', 
# 'params_per_gpu',
# 'params_of_model_=_params_per_gpu_*_mp_size', 'fwd_macs_per_gpu',
# 'fwd_flops_per_gpu', 
# 'fwd_flops_of_model_=_fwd_flops_per_gpu_*_mp_size',
# 'fwd_latency', 
# 'fwd_flops_per_gpu_=_fwd_flops_per_gpu_/_fwd_latency',
# 'bwd_latency',
# 'bwd_flops_per_gpu_=_2_*_fwd_flops_per_gpu_/_bwd_latency',
# 'fwd+bwd_flops_per_gpu_=_3_*_fwd_flops_per_gpu_/_(fwd+bwd_latency)',
# 'step_latency', 
# 'iter_latency',
# 'flops_per_gpu_=_3_*_fwd_flops_per_gpu_/_iter_latency',
# 'samples/second'

# xy_pairs: list of (x_cols, y_col) where x_cols is *either*
#             a single column name or a list/tuple of column names.
# filters: optional dict  {col_name: value_or_iterable}  to keep only
#             matching rows before plotting.
plotting:
  xy_pairs:
    - [total_gpus, samples/second]
    - [total_gpus, flops_per_gpu_=_3_*_fwd_flops_per_gpu_/_iter_latency]
    - [total_gpus, fwd_latency]
    - [total_gpus, bwd_latency]
    - [total_gpus, step_latency]
    - [total_gpus, iter_latency]

  filters:
    dataloader: [torch]
  
  name: training_infrastructure_benchmark_4d_torch_loader.png