#!/bin/bash
set -euo pipefail

HOST_HOME="/host-home"
USER_HOME="${HOME:-/home/ubuntu}"
LOCAL_BIN="${USER_HOME}/.local/bin"

link_host_file() {
  local name="$1"
  if [ -e "${HOST_HOME}/${name}" ]; then
    ln -sfn "${HOST_HOME}/${name}" "${USER_HOME}/${name}"
  fi
}

link_host_dir() {
  local name="$1"
  if [ -d "${HOST_HOME}/${name}" ]; then
    ln -sfn "${HOST_HOME}/${name}" "${USER_HOME}/${name}"
  fi
}

configure_git_identity() {
  local name email
  name="$(git config --file "${HOST_HOME}/.gitconfig" user.name 2>/dev/null || true)"
  email="$(git config --file "${HOST_HOME}/.gitconfig" user.email 2>/dev/null || true)"
  [ -n "${name}" ]  && git config --global user.name  "${name}"
  [ -n "${email}" ] && git config --global user.email "${email}"
}

detect_host_user() {
  if [ -n "${HOST_USER:-}" ]; then
    echo "${HOST_USER}"
    return
  fi

  local user
  user="$(grep -m1 'export ZSH=' "${HOST_HOME}/.zshrc" 2>/dev/null | sed -n 's#.*"/home/\([^/"]*\)/.*#\1#p')"
  if [ -n "${user}" ]; then
    echo "${user}"
    return
  fi

  basename "${HOST_HOME}"
}

remap_host_path() {
  local path="$1"
  local host_user="$2"
  echo "${path}" | sed \
    -e "s|/home/${host_user}/.oh-my-zsh|\${HOME}/.oh-my-zsh|g" \
    -e "s|/home/${host_user}|/host-home|g" \
    -e "s|/scratch/${host_user}|/scratch|g"
}

link_host_local_bin() {
  local host_user="$1"
  local host_bin="${HOST_HOME}/.local/bin"

  mkdir -p "${LOCAL_BIN}"
  [ -d "${host_bin}" ] || return 0

  for entry in "${host_bin}"/*; do
    [ -e "${entry}" ] || [ -L "${entry}" ] || continue

    local name target fixed_target
    name="$(basename "${entry}")"

    if [ -e "${LOCAL_BIN}/${name}" ] && [ ! -L "${LOCAL_BIN}/${name}" ]; then
      continue
    fi

    if [ -L "${entry}" ]; then
      target="$(readlink "${entry}")"
      fixed_target="$(remap_host_path "${target}" "${host_user}")"
      ln -sfn "${fixed_target}" "${LOCAL_BIN}/${name}"
    else
      ln -sfn "${entry}" "${LOCAL_BIN}/${name}"
    fi
  done
}

ensure_writable_local_share() {
  local share_dir="${USER_HOME}/.local/share"

  if [ -L "${share_dir}" ]; then
    rm -f "${share_dir}"
  fi

  mkdir -p "${share_dir}"
}

install_fasd() {
  local fasd_dir="${USER_HOME}/.local/share/fasd"
  mkdir -p "${LOCAL_BIN}"
  ensure_writable_local_share

  if [ -x "${LOCAL_BIN}/fasd" ]; then
    return 0
  fi

  if [ ! -f "${fasd_dir}/fasd" ]; then
    git clone --depth 1 https://github.com/clvv/fasd.git "${fasd_dir}"
    make -C "${fasd_dir}" PREFIX="${USER_HOME}/.local" install
  fi
}

write_zsh_wrapper() {
  local host_user="$1"

  if [ -L "${USER_HOME}/.zshrc" ] || [ -f "${USER_HOME}/.zshrc" ]; then
    rm -f "${USER_HOME}/.zshrc"
  fi

  cat >"${USER_HOME}/.zshrc" <<EOF
# Generated by .devcontainer/setup-shell.sh
# Sources the host zshrc with path remapping for the container environment.

export ZSH="\${ZSH:-\$HOME/.oh-my-zsh}"
export PATH="\${HOME}/.local/bin:\${PATH}"

if [[ -f /host-home/.zshrc ]]; then
  source <(sed \\
    -e "s|/home/${host_user}/.oh-my-zsh|\\\$HOME/.oh-my-zsh|g" \\
    -e "s|/home/${host_user}|/host-home|g" \\
    -e "s|/scratch/${host_user}|/scratch|g" \\
    /host-home/.zshrc)
fi
EOF
}

write_bash_wrapper() {
  local host_user="$1"
  local bashrc="${USER_HOME}/.bashrc"
  if [ -f "${bashrc}" ] && ! [ -L "${bashrc}" ] && grep -qF 'Generated by .devcontainer/setup-shell.sh' "${bashrc}" 2>/dev/null; then
    return 0
  fi

  if [ -L "${bashrc}" ]; then
    rm -f "${bashrc}"
  elif [ -f "${bashrc}" ]; then
    mv "${bashrc}" "${bashrc}.container-default"
  fi

  cat >"${bashrc}" <<EOF
# Generated by .devcontainer/setup-shell.sh
export PATH="\${HOME}/.local/bin:\${PATH}"

if [ -f "${USER_HOME}/.bashrc.container-default" ]; then
  . "${USER_HOME}/.bashrc.container-default"
fi

if [ -f /host-home/.bashrc ]; then
  source <(sed \\
    -e "s|/home/${host_user}/.oh-my-zsh|\${HOME}/.oh-my-zsh|g" \\
    -e "s|/home/${host_user}|/host-home|g" \\
    -e "s|/scratch/${host_user}|/scratch|g" \\
    /host-home/.bashrc)
fi
EOF
}

if [ ! -d "${HOST_HOME}" ]; then
  echo "Host home not mounted at ${HOST_HOME}; keeping container shell defaults."
  exit 0
fi

HOST_USER="$(detect_host_user)"
configure_git_identity
link_host_file ".p10k.zsh"
link_host_dir ".oh-my-zsh"
link_host_dir ".config"
link_host_dir ".local/share"

install_fasd
link_host_local_bin "${HOST_USER}"
write_zsh_wrapper "${HOST_USER}"
write_bash_wrapper "${HOST_USER}"
