defaults:
  - maskdino_backbone
  - _self_

backbone_embed_dims: 
  - ${models.backbones.masked_encoder.embed_dim} # [1024, 1024, 1024, 1024]x4 if using all layers
  - ${models.backbones.masked_encoder.embed_dim}
  - ${models.backbones.masked_encoder.embed_dim}
  - ${models.backbones.masked_encoder.embed_dim}
out_layers: [10, 14, 18, 23]  # backbone block indices for strides 4,8,16,32
adapter_out_layers: [0, 1, 2, 3]  # output all adapter features; encoder picks via transformer_in_features
backbone_output_format: feature