defaults:
  - clusters: local                          # configs/clusters/local.yaml
  - datasets: pretrain_dataset               # configs/datasets/pretrain_dataset.yaml
  - models: jepa/tiny                         # configs/models/jepa/tiny.yaml
  - hooks: hooks                             # configs/hooks/hooks.yaml
  - checkpoint: checkpoint                   # configs/checkpoint/checkpoint.yaml
  - loggers: loggers                         # configs/loggers/loggers.yaml
  - evaluation: base_evaluator               # configs/evaluation/base_evaluator.yaml
  - deepspeed: zero3                         # configs/deepspeed/zero3.yaml
  - optimizers: lamb                         # configs/optimizers/lamb.yaml
  - schedulers: warmup_cosine_decay     # configs/schedulers/warmup_cosine_decay.yaml
  - env: env                                 # configs/env/env.yaml
  - _self_

# overrides
# --------------------------------------------------------------------------------

# clusters
clusters:
  batch_size: 1 # total batch size
  docker_image: null
  apptainer_image: /clusterfs/nvme/hph/env_images/develop_torch_cuda_12_8_ops3d_v2.sif
  script: ${clusters.repo_path}/training/run.py
  mount_path: /clusterfs/nvme/segment_4d
  repo_name: cell_observatory_platform
  repo_path: /clusterfs/nvme/hph/git_managed/${clusters.repo_name}
  outdir: ${outdir}/ray_cluster_logs
  mem_per_cpu: 31000

# data 
datasets:
  # mainly used by other configs but determined here for ease of access
  batch_size: ${clusters.batch_size_per_gpu} # batch size = (total_batch_size * total_gpus)
  input_shape: [32, 128, 128, 128, 2] 
  patch_shape: [4, 16, 16, 16]

  split: 0.1
  dataloader_type: torch
  return_dataloader: true
  distributed_sampler: true
  collate_fn: ${datasets.masking.collate_fn}
  
  dataset:
    _target_: data.datasets.pretrain_dataset.PretrainDataset/
    input_layout: 
      _target_: data.data_shapes.MULTICHANNEL_4D_HYPERCUBE
      value: TZYXC

# model
models:
  _target_: models.jepa.JEPA
  preprocessor: null
    # _target_: models.preprocessor.PreProcessor
    # sample_object:
    #   _target_: data.structures.data_sample.DataSample
  input_fmt: BTZYXC
  input_shape: ${eval:"[${clusters.batch_size_per_gpu}] + ${datasets.input_shape}"}
  temporal_patch_size: ${datasets.patch_shape.0}
  lateral_patch_size: ${datasets.patch_shape.1}
  axial_patch_size: ${datasets.patch_shape.2}

  embed_dim: 192
  predictor_embed_dim: 96
  depth: 12
  predictor_depth: 3
  num_heads: 3
  predictor_num_heads: 3
  mlp_ratio: 4.0

  proj_drop_rate: 0.0
  att_drop_rate: 0.0
  drop_path_rate: 0.1
  init_std: 0.02
  fixed_dropout_depth: false
  use_conv_proj: false
  norm_layer: RmsNorm
  act_layer: SiLU
  mlp_layer: SwiGLU

  mask_ratio: 0.75
  window_mask_shape: null

# checkpointing
checkpoint:
  # for resuming training from previous checkpoint
  resume_run: false # whether to resume from a previous run
  checkpoint_tag: latest_model
  # state_dict_filter_fn: null

  # used by Ray Report
  ray_checkpoint_config:
    num_to_keep: 3
    checkpoint_score_attribute: ${evaluation.val_metric}
    checkpoint_score_order: min
  
  checkpoint_manager:
    _target_: training.checkpoint.CheckpointManager
    pretrained_checkpointdir: null
    resume_checkpointdir: /clusterfs/nvme/segment_4d/test_17/checkpoints
    save_checkpointdir: ${outdir}/checkpoints # directory to save checkpoints
    engine: ${engine} # engine to use for training
    max_keep: 3 # maximum number of checkpoints to keep
    load_dtype: ${quantization}

# evaluation
evaluation:
  val_begin: 0
  val_interval: 1
  # used by BestMetricSaver to save best metric
  # needs to match one of metrics saved per epoch by loss_dict
  # in the training loop or evaluator.evaluate() in the evaluation loop
  val_metric: val_step_loss
  val_mode: lt # mode for the validation metric, can be 'gt' or 'lt'
  evaluator:
    _target_: evaluation.base_evaluation.BaseEvaluator
    training_metrics:
      - "step_loss": "mean"

# logging
loggers:
  logdir: ${outdir}/logs
  event_writers:
    - _target_: training.loggers.LocalEventWriter
      save_dir: ${loggers.logdir}
      step_scalars_prefix: step_logbook
      epoch_scalars_prefix: epoch_logbook
      scalars_save_format: csv

# hooks
hooks:
  hooks_list:
  - _target_: training.hooks.SamplerSetter
  - _target_: training.hooks.LRScheduler
  - _target_: training.hooks.IterationTimer
    warmup_iter: 1
  - _target_: training.hooks.PeriodicWriter
    period: 1000
  - _target_: training.hooks.PeriodicCheckpointer
    period: 1000
    file_prefix: latest_model
  - _target_: training.hooks.BestCheckpointer
    checkpointdir: ${checkpoint.checkpoint_manager.save_checkpointdir}
  - _target_: training.hooks.BestMetricSaver
    metric_name: ${evaluation.val_metric}
    compare_fn: ${evaluation.val_mode}
    eval_after_validation: true
  - _target_: training.hooks.EMASchedulerHook
    ema_start: ${schedulers.ema.0}
    ema_end: ${schedulers.ema.1}

# --------------------------------------------------------------------------------

# experiment name (used for logging)
experiment_name: experiment_pretrain_jepa_2025_06_22

# task
task: pretrain_jepa

# Model type
network: jepa

# engine type
engine: deepspeed

# distributed framework
distributed_framework: ray 

# job type
job_type: train # train or test

# trainer type
trainer: training.loops.EpochBasedTrainer

# training quantization
quantization: float16 # data type for training, options: float32, float16

# base output directory for logs, checkpoints, etc.
outdir: /clusterfs/nvme/segment_4d/test_22