# @package _global_

defaults:
  - clusters: local                          # configs/clusters/local.yaml
  - datasets: local/ao                       # configs/datasets/local/ao.yaml
  - models: baseline/tiny                    # configs/models/baseline/tiny.yaml
  - deepspeed: zero3                         # configs/deepspeed/zero3.yaml
  - optimizers: lamb                         # configs/optimizers/lamb.yaml
  - schedulers: test_warmup_cosine_decay     # configs/schedulers/warmup_cosine_decay.yaml
  - _self_

paradigm: training.backend.supervised

outdir: /opt/project/pretrained_models/baseline-tiny
logdir: ${outdir}/logs
checkpointdir: ${outdir}/checkpoints

# Override shape
models:
  input_fmt: BZYXC
  input_shape: [1, 6, 64, 64, 1]
  modes: 15 # number of zernikes modes to predict

checkpoint_update_interval: 1 # save checkpoint every N epochs
load_checkpointdir: null # specify if we want to load a checkpoint from a previous run that is not latest local run
profile: false

batch_size: 512
