defaults:
  - paths: janelia                           # configs/paths/janelia.yaml
  - hydra: overrides                         # configs/hydra/overrides.yaml (not working)
  - clusters: janelia_h100                   # configs/clusters/janelia_h100.yaml
  - datasets: pretrain_dataset               # configs/datasets/pretrain_dataset.yaml
  - models: mae/base                         # configs/models/mae/base.yaml
  - hooks: hooks                             # configs/hooks/hooks.yaml
  - checkpoint: checkpoint                   # configs/checkpoint/checkpoint.yaml
  - loggers: loggers                         # configs/loggers/loggers.yaml
  - evaluation: base_evaluator               # configs/evaluation/base_evaluator.yaml
  - deepspeed: zero3                         # configs/deepspeed/zero3.yaml
  - optimizers: lamb                         # configs/optimizers/lamb.yaml
  - schedulers: test_warmup_cosine_decay     # configs/schedulers/test_warmup_cosine_decay.yaml
  - _self_


# experiment name (used for logging)
experiment_name: experiment_pretrain_mae

# task
task: pretrain_mae

# Model type
network: mae

# engine type
engine: deepspeed

# distributed framework
distributed_framework: ray

# job type
job_type: train # train or test

# trainer type
trainer: training.loops.EpochBasedTrainer

# training quantization
quantization: float16 # data type for training, options: float32, float16


# overrides
# --------------------------------------------------------------------------------

paths:
  # base output directory for logs, checkpoints, etc.
  outdir: ${paths.data_path}/thayer/pretrained_models/${experiment_name}


clusters:
  batch_size: 128 # total batch size
  worker_nodes: 1 # number of worker nodes
  gpus_per_worker: 8 # number of gpus per worker node
  cpus_per_gpu: 4 # number of cpu cores per gpu


datasets:
  # mainly used by other configs but determined here for ease of access
  batch_size: ${clusters.batch_size_per_gpu} # batch size = (total_batch_size * total_gpus)
  input_shape: [16, 128, 128, 128, 2] # NOTE: important that this matches database hypercube shape
  patch_shape: [4, 16, 16, 16]

  split: 0.1

  max_rois: null # maximum number of ROIs (each ROI can have dozens of tiles)
  max_tiles: null # maximum number of tiles (each tile can have thousands of hypercubes)
  max_hypercubes: 1000 # maximum number of hypercubes to return

  
  dataset:
    _target_: data.datasets.pretrain_dataset.PretrainDataset
    input_layout: 
      _target_: data.data_shapes.MULTICHANNEL_4D_HYPERCUBE
      value: TZYXC


models:
  _target_: models.maskedautoencoder.MaskedAutoEncoder
  input_fmt: BTZYXC
  input_shape: ${eval:"[${clusters.batch_size_per_gpu}] + ${datasets.input_shape}"}
  temporal_patch_size: ${datasets.patch_shape.0}
  lateral_patch_size: ${datasets.patch_shape.1}
  axial_patch_size: ${datasets.patch_shape.2}


evaluation:
  val_begin: 0
  val_interval: 1
  # used by BestMetricSaver to save best metric
  # needs to match one of metrics saved per epoch by loss_dict
  # in the training loop or evaluator.evaluate() in the evaluation loop
  val_metric: val_step_loss
  val_mode: lt # mode for the validation metric, can be 'gt' or 'lt'
  evaluator:
    _target_: evaluation.base_evaluation.BaseEvaluator
    training_metrics:
      - "step_loss": "mean"
