# @package _global_
defaults:
  - /paths/abc
  - /clusters/local
  - /datasets/pretrain_dataset
  - /checkpoint/checkpoint
  - /evaluation/base_evaluator
  - /hooks/hooks
  - _self_

# number of batches to run benchmark for and
# number of warmup batches to run before measuring performance
warmup: ${eval:"(${benchmark_params.num_workers}[-1]*${benchmark_params.prefetch_factors}[-1]) + 1"}
num_batches: 50

# where to save the benchmark results
csv_out: ${paths.outdir}/results/results.csv

# whether to benchmark the main process
benchmark_main_process: true

# whether to benchmark the worker processes
# benchmark_worker_process: true

# worker init function to use for the dataloader
# worker_init_fn:
#   _target_: scripts.benchmark_dataloaders.WorkerInit
#   out_dir: ${paths.outdir}/results

# benchmark loop to run for each worker
loop_per_worker_script: scripts.benchmark_dataloaders.bench_dataloader

# experiment name
experiment_name: benchmark_dataloaders_4d
wandb_project: platform_benchmarks

# run type
run_type: single_run # single_run, multi_run, or tune

# this is poorly named but this will prevent
# dataloaders from being automatically wrapped
# with prepare_data_loader by Ray which 
# allows us to control moving data
# to device manually 
distributed_framework: manual

# dtype for training data
dataset_dtype: float16 # data type for training, options: float32, float16

# dataset layout in the zarr files
dataset_layout_order: TZYXC

# overrides
# --------------------------------------------------------------------------------

paths:
  # base output directory for logs, checkpoints, etc.
  outdir: ${paths.data_path}/pretrained_models/benchmarks_test/dataloaders/runs

datasets:
  input_shape: [16, 128, 128, 128, 2]
  patch_shape: [4, 16, 16, 16]

  split: 0.0 # no split for benchmarking
  max_hypercubes: 100000


clusters:
  launcher_type: local # type of launcher to use

  worker_nodes: 1 # number of worker nodes
  gpus_per_worker: 1 # number of gpus per worker node
  cpus_per_gpu: 16 # number of cpu cores per gpu
  # NOTE: to ensure that we can benchmark the dataloaders
  #       without running into memory issues.
  mem_per_cpu: 31000 # ram per cpu core

# Intra-Node Benchmarking Configuration (will sweep Cartesian product of the lists for a given cluster size)
# ----------------------------------------------------------------------------------------------------------

benchmark_params:
  batch_size: [1] # 1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024
  num_workers: [8] # 4, 8
  prefetch_factors: [1] # 1, 2, 4, 8