# @package _global_
defaults:
  - /paths/abc                               # configs/paths/abc.yaml
  - /hydra/overrides                         # configs/hydra/overrides.yaml (not working)
  - /clusters/local                          # configs/clusters/local.yaml
  - /datasets/pretrain_dataset_ray               # configs/datasets/pretrain_dataset.yaml
  - /models/mae/large                        # configs/models/mae/large.yaml
  - /hooks/hooks                             # configs/hooks/hooks.yaml
  - /checkpoint/checkpoint                   # configs/checkpoint/checkpoint.yaml
  - /loggers/loggers                         # configs/loggers/loggers.yaml
  - /evaluation/base_evaluator               # configs/evaluation/base_evaluator.yaml
  - /deepspeed/zero2                         # configs/deepspeed/zero2.yaml
  - /optimizers/lamb                         # configs/optimizers/lamb.yaml
  - /schedulers/test_warmup_cosine_decay     # configs/schedulers/test_warmup_cosine_decay.yaml
  - /optimizations/optimizations             # configs/optimizations/optimizations.yaml
  - _self_

# experiment name (used for logging)
experiment_name: performance_profiling
wandb_project: test_ray_dataset_v2

# task
task: pretrain_mae

# Model type
network: mae

# engine type
engine: deepspeed

# distributed framework
distributed_framework: ray

# run type
run_type: single_run # single_run, multi_run, or tune

# job type
job_type: train # train or test

# trainer type
trainer: training.loops.EpochBasedTrainer

# loop per worker script
loop_per_worker_script: training.loops.train_loop_per_worker

# training quantization
quantization: bfloat16 # data type for training, options: float32, float16

# dtype for training data
dataset_dtype: bfloat16 # data type for training, options: float32, float16

# dataset layout in the zarr files
dataset_layout_order: TZYXC

# overrides
# --------------------------------------------------------------------------------

# clusters
clusters:
  ray_queue_memory: 0.3
  batch_size: 96 # total batch size
  worker_nodes: 1 # number of worker nodes
  gpus_per_worker: 3 # number of gpus per worker node
  cpus_per_gpu: 42 # number of cpu cores per gpu
  mem_per_cpu: 21000 # ram per cpu core
  scaling_config:
    use_gpu: true
    num_workers: ${clusters.total_gpus} # number of total workers (equals total nr. gpus normally)
    resources_per_worker:
      CPU: 0
      GPU: 1
    trainer_resources:
      CPU: 0 

#paths:
paths:
  # base output directory for logs, checkpoints, etc.
  outdir: ${paths.data_path}/pretrained_models/${experiment_name}
  resume_checkpointdir: null 
  pretrained_checkpointdir: null

# data
datasets:
  # mainly used by other configs but determined here for ease of access
  batch_size: ${clusters.batch_size_per_gpu} # batch size = (total_batch_size * total_gpus)
  input_shape: [16, 128, 128, 128, 2] # NOTE: important that this matches database hypercube shape
  patch_shape: [4, 16, 16, 16]

  split: 0.1
  return_dataloader: true
  distributed_sampler: true

  use_arrow_tensor_v2: true # use Arrow Tensor v2 for better performance
  locality_with_output: true # whether to use locality with output for the Ray tasks

  # ray_remote_args:
  #   num_cpus: 0.25 # number of cpus per gpu for Ray tasks

  impl_type: FixedSizeListArray # implementation type for the data tensor array, options: FixedShapeTensorArray, FixedSizeListArray
  ray_data_v2: true # whether to use Ray Data v2 (experimental loader)
  
  prefetch_factor: 3
  num_actors_min: 4
  num_actors_max: 64
  
  with_batched_api: true
  context:
    file_io_concurrency: null # concurrency for file I/O operations
    data_copy_concurrency: null # concurrency for data copy operations
    cache_pool: 
      total_bytes_limit: 0

  databases:
    max_rois: null # maximum number of ROIs (each ROI can have dozens of tiles)
    max_tiles: null # maximum number of tiles (each tile can have thousands of hypercubes)
    max_hypercubes: 80000 # maximum number of hypercubes to return
    use_cached_hypercubes_dataframe: true
    hypercubes_dataframe_path: ${paths.outdir}/database/hypercubes_dataframe.csv
    protocol: cursor # protocol used to fetch data from source (default is 'binary', can also be 'csv' or 'cursor')

# schedulers
schedulers:
  epochs: 1

# turn on compile mode
# optimizations:
#   torch_compile:
#     enabled: true
#     mode: reduce-overhead
#     dynamic: false

# drop_path in timm leads to graph break in compile
# models:
#   mae:
#     drop_path_rate: 0.0 # no drop path rate for now

# # flops profiler needs to be turned off for compile
# deepspeed:
#   flops_profiler:
#     enabled: false # turn off flops profiler for now

# hooks
hooks:
  # nsys_env:
  #   nsight: 
  #     pytorch: autograd-shapes-nvtx
  #     t: cuda,nvtx,cudnn,cublas,osrt
  #     s: cpu
  #     "gpu-metrics-devices": all
  #     capture-range: cudaProfilerApi
  #     capture-range-end: stop-shutdown
  hooks_list:
  # - _target_: training.hooks.NsysProfilerHook
  #   start_iter: 20
  #   end_iter: 25
  # - _target_: training.hooks.AnomalyDetector
  - _target_: training.hooks.LRScheduler
  - _target_: training.hooks.IterationTimer
  - _target_: training.hooks.PeriodicWriter
  - _target_: training.hooks.PeriodicCheckpointer
    period: 100
    file_prefix: latest_model
  - _target_: training.hooks.BestCheckpointer
    checkpointdir: ${checkpoint.checkpoint_manager.save_checkpointdir}
  - _target_: training.hooks.TorchMemoryStats
    step_period: 2
    epoch_period: 1
    logdir: ${loggers.logdir}
  - _target_: training.hooks.BestMetricSaver
    metric_name: ${evaluation.val_metric}
    compare_fn: ${evaluation.val_mode}
    eval_after_validation: true