defaults:
  - _self_

hooks_list:
- _target_: training.hooks.SamplerSetter
- _target_: training.hooks.LRScheduler
- _target_: training.hooks.IterationTimer
  warmup_iter: 1
- _target_: training.hooks.PeriodicWriter
  period: 1
- _target_: training.hooks.PeriodicCheckpointer
  period: 1
  file_prefix: latest_model
- _target_: training.hooks.BestCheckpointer
  checkpointdir: ${checkpoint.checkpoint_manager.save_checkpointdir}
# - _target_: training.hooks.TorchProfiler
#   output_dir: ${loggers.logdir}/profiler
#   schedule:
#     skip_first: 1
#     warmup: 1
#     active: 3
#     repeat: 2
#     wait: 1  
#   activities: 
#     - CUDA
#     - CPU
#   save_tensorboard: true
# - _target_: training.hooks.TorchMemoryStats
#   step_period: 100
#   epoch_period: 1
#   max_runs: 10
#   logdir: ${loggers.logdir}
- _target_: training.hooks.BestMetricSaver
  metric_name: ${evaluation.val_metric}
  compare_fn: ${evaluation.val_mode}
  eval_after_validation: true
# - _target_: training.hooks.EarlyStopHook
#   patience: 10
#   stopping_threshold: 0.01
#   mode: ${evaluation.val_mode}
#   metric_name: ${evaluation.val_metric}