defaults:
  - databases: base_database  # Loads configs/datasets/databases/base_database.yaml
  - masking: mask_generator       # Loads configs/datasets/masking/mask_generator.yaml
  - transforms: dali_transforms        # Loads configs/datasets/transforms/dali_transforms.yaml
  - preprocessor: dali_preprocessor  # Loads configs/datasets/preprocessor/dali_preprocessor.yaml
  - _self_

# mainly used by other configs but determined here for ease of access
batch_size: ${clusters.batch_size_per_gpu} # batch size = (total_batch_size * total_gpus)
input_shape: [16, 128, 128, 128, 2] 
patch_shape: [4, 16, 16, 16]

max_rois: null # maximum number of ROIs (each ROI can have dozens of tiles)
max_tiles: null # maximum number of tiles (each tile can have thousands of hypercubes)
max_hypercubes: null # maximum number of hypercubes to return

hpf_list: null # list of specific HPFs (hours-post-fertilization in hours) to filter
roi_list: null # list of specific ROIs to filter
tile_list: null # list of specific tiles to filter
synthetic_only: False
has_annotations: False

occupancy_threshold: 0. # to filter our hypercubes with less than this occupancy ratio (0.0-1.0)

use_cached_hypercubes_dataframe: false # whether to use the cached hypercubes dataframe
hypercubes_dataframe_path: ${paths.outdir}/database/hypercubes_dataframe.csv # path to the hypercubes dataframe (path/to/repo/databases/default_hypercubes_dataframe.csv)
server_folder_path: ${paths.server_folder_path}

split: 0.2
return_dataloader: true
distributed_sampler: true
collate_fn: null
prefetch_factor: 2 # prefetch factor for the dataloader
num_workers: ${clusters.cpus_per_worker}  # number of workers for the dataloader

exec_async: true
exec_pipelined: true


dataset:
  _target_: cell_observatory_platform.data.datasets.pretrain_dataset_dali.PretrainDatasetDali
  dtype: ${dataset_dtype}
  hypercubes_dataframe_path: ${datasets.hypercubes_dataframe_path}
  server_folder_path: ${datasets.server_folder_path}
  max_rois: ${datasets.max_rois}
  max_tiles: ${datasets.max_tiles}
  max_hypercubes: ${datasets.max_hypercubes}
  hpf_list: ${datasets.hpf_list}
  roi_list: ${datasets.roi_list}
  tile_list: ${datasets.tile_list}
  synthetic_only: ${datasets.synthetic_only}
  has_annotations: ${datasets.has_annotations}
  time: true

  input_layout:
    _target_: cell_observatory_platform.data.data_shapes.MULTICHANNEL_HYPERCUBE
    value: ${dataset_layout_order}

dali_last_batch_policy:
  _target_: nvidia.dali.plugin.base_iterator.LastBatchPolicy
  _args_:  [1] # 0=FILL, 1=DROP, 2=PARTIAL
