defaults:
  - databases: supabase_database  # Loads configs/datasets/databases/supabase_database.yaml
  - masking: mask_generator       # Loads configs/datasets/masking/mask_generator.yaml
  - transforms: transforms        # Loads configs/datasets/transforms/transforms.yaml
  - _self_

# mainly used by other configs but determined here for ease of access
batch_size: ${clusters.batch_size_per_gpu} # batch size = (total_batch_size * total_gpus)
input_shape: [32, 128, 128, 128, 2] 
patch_shape: [4, 16, 16, 16]

split: 0.1
dataloader_type: torch
return_dataloader: true
distributed_sampler: true
collate_fn: ${datasets.masking.collate_fn}

databases:
  max_rois: null # maximum number of ROIs (each ROI can have dozens of tiles)
  max_tiles: null # maximum number of tiles (each tile can have thousands of hypercubes)
  max_hypercubes: 100 # maximum number of hypercubes to return

dataset:
  _target_: data.datasets.pretrain_dataset.PretrainDataset
  server_folder_path: ${paths.server_folder_path}
  hypercubes_dataframe_path: ${paths.outdir}/database/hypercubes_dataframe.csv
  input_layout: 
    _target_: data.data_shapes.MULTICHANNEL_4D_HYPERCUBE
    value: TZYXC