activation_checkpoint:
  enable: false
  modules:
    - ["input_encoder.encoder", "blocks"]
    - ["target_predictor.decoder", "transformer_blocks"]
  selective_ac_option: 2
  per_op_sac_force_recompute_mm_shapes_by_fqns: null
  mode: "selective"
  mm_recompute_frac: 2

torch_compile:
  enable: false
  modules:
    - ["input_encoder.encoder", "blocks"]
    - ["target_predictor.decoder", "transformer_blocks"]
  range: block_based
  mode: null
  dynamic: false
  blockbased_fullgraph: false
  enable_compiled_autograd: false
  backend: inductor
