name: delete old unused container images
on:
  schedule:
    - cron: "0 13 * * 1" 
    # Every Monday at 1PM UTC (9AM EST)
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
permissions:
  packages: write
  contents: read

jobs:
  list_package_info:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - env:
          GH_TOKEN: ${{ secrets.cleanup_packages }}
          ORG: ${{ github.repository_owner }}
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /orgs/$ORG/packages?package_type=container


  clean-ghcr:
    name: Delete old tagged
    runs-on: ubuntu-latest
    steps:
      - name: Delete old tagged images
        uses: snok/container-retention-policy@4f22ef80902ad409ed55a99dc5133cc1250a0d03    # v3.0.0
        with:
          tag-selection: tagged
          image-names: "*"      # cell_observatory_platform, aovift, ...
          cut-off: 1w           # package versions should be older than 1 week, to be considered
          keep-n-most-recent: 3
          account: ${{ github.repository_owner }}    # Organization "cell-observatory"
          token: ${{ secrets.cleanup_packages }}

  clean-ghcr-untagged:
    name: Delete old untagged
    runs-on: ubuntu-latest
    steps:
      - name: Delete old untagged images
        uses: snok/container-retention-policy@4f22ef80902ad409ed55a99dc5133cc1250a0d03    # v3.0.0
        with:
          tag-selection: untagged
          image-names: "*"      # cell_observatory_platform, aovift, ...
          cut-off: 1d           # package versions should be older than 1 week, to be considered
          keep-n-most-recent: 0
          account: ${{ github.repository_owner }}    # Organization "cell-observatory"
          token: ${{ secrets.cleanup_packages }}
          dry-run: false


  clean-ghcr-deleted-branches:
    name: Delete removed branches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Get all branch names
        id: get_branches
        run: |
          git fetch --all
          echo $(git branch -r) 
          echo "Finding all feature branches, converting to format !*feature-branchname* for filtering container tags"
          git branch -r | grep -o "feature/.*" | sed -e 's/^/!*/' | sed -e 's/$/*/' | tr '/' '-' > all_feature_branches_names.txt  
          echo "Concatenating all branch names into a single line"
          echo "IMAGES_FILTER=$(paste -sd ' '  all_feature_branches_names.txt)"
          echo "IMAGES_FILTER=$(paste -sd ' '  all_feature_branches_names.txt)" >> "$GITHUB_OUTPUT"

      - name: Delete old untagged images
        uses: snok/container-retention-policy@4f22ef80902ad409ed55a99dc5133cc1250a0d03    # v3.0.0
        env:
          IMAGES_FILTER: ${{ steps.get_branches.outputs.IMAGES_FILTER }}
        with:
          image-names: "*"      # cell_observatory_platform, aovift, ...
          tag-selection: tagged
          image-tags: "!develop* !main* !tags* !0* !1* !2* !3* ${{ steps.get_branches.outputs.IMAGES_FILTER }} *feature-* "  # delete all features that are not active, ...
          cut-off: 1d           # package versions should be older than 1 week, to be considered
          keep-n-most-recent: 0
          account: ${{ github.repository_owner }}    # Organization "cell-observatory"
          token: ${{ secrets.cleanup_packages }}
          dry-run: false